@baseUrl = http://localhost:3333
@authToken = {{Authentication.response.body.access_token}}

# @name Create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@email.com",
    "password": "Pass123"
}

###

# @name Authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "johndoe@email.com",
    "password": "Pass123"
}

###

# @name CreateQuestion
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "New Question",
    "content": "Question Content"
}
